
server {
    listen 80;
    server_name localhost;

    # Скрытие версии Nginx
    server_tokens off;

    # Ограничение размера загружаемых файлов (защита от переполнения)
    client_max_body_size 10M;

    location / {
        proxy_pass http://suomi_app:8000;
        proxy_set_header Host ;
        proxy_set_header X-Real-IP ;
        proxy_set_header X-Forwarded-For ;
        proxy_set_header X-Forwarded-Proto ;
    }
}
